config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  resources :accounts, except: [:index, :destroy]
  resources :addresses, except: [:index, :show]
  resources :orders, except: [:edit, :update]
  resources :posts, except: [:index]
  namespace :admin do
  	resources :accounts
  	resources :addresses
  	resources :orders do
      collection do
        get :processed, :unprocessed
      end
    end

  end
end

app/models/order.rb
class Order < ApplicationRecord
	# associations
	belongs_to :account

	#validations
	validates :num_shields, presence: true,
							numericality: { only_integer: true,
											less_than_or_equal_to: 999 }
	validates :num_adjusters, presence: true,
							  numericality: { only_integer: true,
											less_than_or_equal_to: 999 }
	validates :message, presence: true, length: { maximum: 140 }
	validates :street_address, presence: true, length: { maximum: 100 }
	validates :city, presence: true
	validates :state, presence: true
	validates :zipcode, presence: true, length: { is: 5 }, numericality: true

	def process
	  self.processed = true
	  save!
	end

	def unprocess
	  self.processed = false
	  save!
	end
end

app/controllers/admin/orders_controller.rb
module Admin
  class OrdersController < ApplicationController
    before_action :order_processed?, only: [:destroy]
  	def index
  	  @processed = Order.where("processed = true")
  	  @unprocessed = Order.where("processed = false")
  	end

  	def show
  	 @order = Order.find(params[:id])
  	end

  	def processed
  	  @processed = Order.where("processed = true")		
  	end

  	def unprocessed
  	  @unprocessed = Order.where("processed = false")
  	end

    def update
      @order = Order.find(params[:id])
      puts "ay"
      if params[:process] == "true"
        puts "process!"
        p @order
        @order.process
        p @order
        redirect_to admin_order_path(@order)
      elsif params[:process] == "false"
        puts "wrong"
        @order.unprocess
        redirect_to admin_order_path(@order)
      end
    end

    def destroy
      @order.destroy
      flash[:success] = "Order ##{@order.id} deleted!"
      redirect_to admin_orders_path
    end

    private

      def order_processed?
        @order = Order.find(params[:id])
        p @order
        unless @order.processed?
          redirect_to admin_orders_path
        end
      end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_action :account_set_up?
	before_action :has_address?
	before_action :my_order?, only: [:show, :destroy]
	before_action :order_processed?, only: [:destroy]
	before_action :is_admin?

	def index
		if current_user.admin?
			@orders = Order.order('created_at DESC')
		else
			@processed_orders = current_user_account.orders.where("processed = true")
			@unprocessed_orders = current_user_account.orders.where("processed = false")
		end
	end

	def show
		@order = Order.find(params[:id])
	end

	def new
	  @order = Order.new
	end

	def create
	  order_attributes = order_params
	  
	  if (address_id = order_params[:address_id])
	  	address = Address.find(address_id)
	  	order_attributes[:street_address] = address[:street_address]
	  	order_attributes[:city] = address[:city]
	  	order_attributes[:state] = address[:state]
	  	order_attributes[:zipcode] = address[:zipcode]
	  end
	  order_attributes.delete(:address_id)
	  @order = current_user_account.orders.build(order_attributes)
	  if @order.save
	  	flash[:success] = "Order placed!"
	  	redirect_to order_path(@order)
	  	#OrderMailer.confirmation(current_user, @order).deliver_now
	  else
	  	render :new
	  end
	end

	def destroy
	  flash[:success] = "Order canceled!"
	  
	  #OrderMailer.cancellation(current_user, @order).deliver_now
	  #AdminMailer.cancellation(current_user, @order).deliver_now
	  @order.destroy
	  redirect_to root_path
	end

	private

	  def order_params
	  	params.require(:order).permit(:num_shields, :num_adjusters,
	  								  :message, :street_address, :city,
	  								  :state, :zipcode, :address_id)
	  end

	  def account_set_up?
	  	if !current_user_account && !current_user.admin?
	  	  flash[:alert] = "Finish account set up before placing order."
	  	  store_location
	  	  redirect_to new_account_path
	  	end
	  end

	  def has_address?
	  	if !current_user.admin? && current_user_account.addresses.empty?
	  	  flash[:alert] = "Add address to your account before placing order."
	  	  store_location
	  	  redirect_to new_address_path
	    end
	  end

	  def my_order?
	  	unless current_user.admin?
	  	  @order = current_user_account.orders.find_by(id: params[:id])
	  	  redirect_to root_url if @order.nil?
	  	end
	  end

	  def order_processed?
	  	unless current_user.admin?
	  	  @order = Order.find_by(id: params[:id])
	  	  flash[:notice] = "Your order cannot be cancelled because it's already on the way!
	  	  					You can email our administrator at #{administrator.email} and
	  	  					we can try to work towards a solution."
	  	  redirect_to root_url if @order.processed?
	  	end
	  end

	  def is_admin?
	  	if current_user.admin?
	  	 redirect_to admin_orders_path
	  	end
	  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_order.html.erb
<% @account = order.account %>
<div class="card admin-order">
  <div class="admin-order-header-wrapper" style="background-color: <%= order.processed? ? "#18a83e" : "rgb(131,208,245)" %>;">
  	  <h2 class="admin-order-header">Order #<%= order.id %></h2>
  </div>
  <div class="admin-order-info hide">
	<li class="list-group-item order-info-group">
		<div class="order info order-info">
			<span><b>Email:</b> <%= @account.user.email %></span>
		</div>
		<div class="order info order-info">
			<span><b>Face Shields:</b> <%= order.num_shields %></span>
			<span><b>Mask Adjusters:</b> <%= order.num_adjusters %></span>
		</div>
		<div class="account info order-info">
			<span><b>Recipient:</b> <%= @account.institution_name %></span>
			<span><b>Contact Name:</b> <%= @account.contact_first_name %> <%= @account.contact_last_name %></span>
			<span><b>Phone Number:</b> <%= @account.phone_number %></span>
		</div>
		<div class="address info order-info">
			<span><b>Street Address:</b> <%= order.street_address %></span>
			<span><b>City:</b> <%= order.city %></span>
			<span><b>State:</b> <%= order.state %></span>
			<span><b>Zip Code:</b> <%= order.zipcode %></span>
		</div>
		<div class="buttons">
		  <% if action_name == "unprocessed" || action_name == "processed" %>
		    <%= link_to admin_orders_path do %>
			  <span class="material-icons">
				library_books
			  </span>
			  <p>all</p>
			<% end %>
		  <% end %>
		  <%= link_to admin_order_path(order) do %>
			  <span class="material-icons">
				visibility
			  </span>
			  <p>view</p>
			<% end %>
		  <% if !order.processed? %>
			<%= link_to admin_order_path(order, process: true), method: :patch do %>
			  <span class="material-icons">
				check_circle
			  </span>
			  <p>process</p>
			<% end %>
		  <% else %>
		    <%= link_to admin_order_path(order, process: false), method: :patch do %>
			  <span class="material-icons">
				backspace
			  </span>
			  <p>unprocess</p>
			<% end %>
			<%= link_to admin_order_path(order), method: :delete do %>
			  <span class="material-icons">
				delete
			  </span>
			  <p>delete</p>
			<% end %>
		  <% end %>
		</div>
	</li>
  </div>
</div>

app/views/admin/orders/index.html.erb
<div class="row">
  <div class="col-md-6">
  	<%= link_to unprocessed_admin_orders_path, class: "right-link" do %>
  	  <h1>Unprocessed</h1>
  	  <span class="material-icons">last_page</span>
  	<% end %>
  	<%= render @unprocessed %>
  </div>
  <div class="col-md-6">
	<%= link_to processed_admin_orders_path, class: "right-link" do %>
  	  <h1>Processed</h1>
  	  <span class="material-icons">last_page</span>
  	<% end %>
  	<%= render @processed %>
  </div>
</div>

app/views/admin/orders/processed.html.erb
<div class="main-wrapper">
    <div class="processed-header-wrapper">
	  <%= link_to admin_orders_path, class: "back-link" do %>
  	    <span class="material-icons">first_page</span>
  	    <p>back</p>
  	  <% end %>
  	  <h1 class="order-header">Processed</h1>
  	</div>
  <%= render @processed %>
</div>

app/views/admin/orders/show.html.erb
<div class="col-md-6">
<% @account = @order.account %>
<div class="card admin-order">
  <div class="admin-order-header-wrapper" style="background-color: <%= @order.processed? ? "#18a83e" : "#c7c7c7" %>;">
  	  <h2 class="admin-order-header">Order #<%= @order.id %></h2>
  </div>
  <div class="admin-order-info">
	<li class="list-group-item order-info-group">
		<div class="order info order-info">
			<span><b>Email:</b> <%= @account.user.email %></span>
		</div>
		<div class="order info order-info">
			<span><b>Face Shields:</b> <%= @order.num_shields %></span>
			<span><b>Mask Adjusters:</b> <%= @order.num_adjusters %></span>
		</div>
		<div class="account info order-info">
			<span><b>Recipient:</b> <%= @account.institution_name %></span>
			<span><b>Contact Name:</b> <%= @account.contact_first_name %> <%= @account.contact_last_name %></span>
			<span><b>Phone Number:</b> <%= @account.phone_number %></span>
		</div>
		<div class="address info order-info">
			<span><b>Street Address:</b> <%= @order.street_address %></span>
			<span><b>City:</b> <%= @order.city %></span>
			<span><b>State:</b> <%= @order.state %></span>
			<span><b>Zip Code:</b> <%= @order.zipcode %></span>
		</div>
		<div class="buttons">
		  <% if !@order.processed? %>
			<%= link_to admin_orders_path do %>
			  <span class="material-icons">
				library_books
			  </span>
			  <p>all</p>
			<% end %>
			<%= link_to admin_order_path(@order, process: true), method: :patch do %>
			  <span class="material-icons">
				check_circle
			  </span>
			  <p>process</p>
			<% end %>
		  <% else %>
			<%= link_to admin_orders_path do %>
			  <span class="material-icons">
				library_books
			  </span>
			  <p>all</p>
			<% end %>
		    <%= link_to admin_order_path(@order, process: false), method: :patch do %>
			  <span class="material-icons">
				backspace
			  </span>
			  <p>unprocess</p>
			<% end %>
			<%= link_to admin_order_path(@order), method: :delete do %>
			  <span class="material-icons">
				delete
			  </span>
			  <p>delete</p>
			<% end %>
		  <% end %>
		</div>
	</li>
  </div>
</div>
</div>

app/views/admin/orders/unprocessed.html.erb
<div class="main-wrapper">
	<div class="processed-header-wrapper">
	  <%= link_to admin_orders_path, class: "back-link" do %>
  	    <span class="material-icons">first_page</span>
  	    <p>back</p>
  	  <% end %>
  	  <h1 class="order-header">Unprocessed</h1>
  	</div>
    <%= render @unprocessed %>
</div>