config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  resources :accounts, except: [:index, :destroy]
  resources :addresses, except: [:index, :show]
  resources :orders, except: [:edit, :update]
  resources :posts, except: [:index]
  namespace :admin do
  	resources :accounts
  	resources :addresses
  	resources :orders do
      collection do
        get :processed, :unprocessed
      end
    end

  end
end

app/views/layouts/_admin_icon_bar.html.erb
<div class="icon-bar">
	<%= link_to root_path do %>
		<span class="material-icons">
			home
		</span>
	<% end %>
	<%= link_to admin_orders_path do %>
		<span class="material-icons">
			library_books
		</span>
	<% end %>
	<%= link_to new_post_path do %>
		<span class="material-icons">
			add_comment
		</span>
	<% end %>

</div>

app/views/layouts/_footer.html.erb
<!--
<footer class="footer">
	hey
</footer>
-->

app/views/layouts/_head.html.erb
<head>
  <title>Operation Face Shield Chicago</title>
  <%= favicon_pack_tag 'media/images/favicon2.png' %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
  <link href="https://fonts.googleapis.com/css2?family=Work+Sans&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Volkhov:ital,wght@1,700&display=swap" rel="stylesheet">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <a class="navbar-brand" href="<%= root_path %>"><%= image_pack_tag 'media/images/banner3.png' %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="material-icons">
      more_vert
    </span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      
      <% if user_signed_in? && !current_user.admin?%>
        <li class="nav-item">
          <%= link_to 'About Us', about_path, class: "nav-link" %>
        </li>
        <li class="nav-item reg-link">
          <%= link_to "Place Order", new_order_path, class: "nav-link dark-blue" %>
        </li>
        <li class="nav-item">
            <%= link_to "Write Post", new_post_path, class: "nav-link reg-link" %>
        </li>
         <% if current_user_account %>
           <% if current_user_account.orders.any? %>
             <li class="nav-item reg-link">
               <%= link_to "View Orders", orders_path, class: "nav-link" %>
             </li>
           <% end %>
           <li class="nav-item">
             <%= link_to "Account", account_path(current_user_account), class: "nav-link" %>
           </li>
         <% else %>
           <li class="nav-item reg-link">
             <%= link_to "Complete Account Set Up", new_account_path, class: "nav-link" %>
           </li>
           <li class="nav-item reg-link">
             <%= link_to user_registration_path, data: { confirm: "Are you sure?" }, method: :delete, class: "nav-link" do %>
               Cancel My Account
             <% end %>
           </li>
         <% end %>
         <li class="nav-item">
           <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "nav-link red" %>
         </li>
      <% elsif user_signed_in? && current_user.admin? %>
        <li class="nav-item admin-link">
             <%= link_to "All Orders", admin_orders_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Write Post", new_post_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
           <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "nav-link red" %>
         </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'About Us', about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
         <%= link_to 'Log in', new_user_session_path, class: "nav-link" %>
        </li>
        
        <li class="nav-item">
         <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_icon_bar.html.erb
<div class="icon-bar">
	<%= link_to root_path do %>
		<span class="material-icons">
			home
		</span>

	<% end %>
	<%= link_to new_order_path do %>
		<span class="material-icons">
			local_shipping
		</span>

	<% end %>
	<%= link_to new_post_path do %>
		<span class="material-icons">
			add_comment
		</span>

	<% end %>
	<%= link_to orders_path do %>
		<span class="material-icons">
			library_books
		</span>

	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
        <div class="dummy"></div>
        <%= render 'shared/links' unless current_user && !current_user.admin?%>
        <% if !flash.empty? %>
          <% flash.each do |msg_type, msg| %>
            <%= content_tag(:div, msg, class: "alert alert-#{msg_type}") %>
          <% end %>
        <% end %>
        <%= yield %>
        <div class="dummy bottom"></div>
    </div>
    <% if current_user && current_user.admin? %>
      <%= render 'layouts/admin_icon_bar' %>
    <% else %>
      <% if current_user && current_user_account %>
        <%= render 'layouts/icon_bar' %>
      <% end %>
    <% end %>
    <%= render 'layouts/footer' %>
  </body>
</html>