config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  resources :accounts, except: [:index, :destroy]
  resources :addresses, except: [:index, :show]
  resources :orders, except: [:edit, :update]
  resources :posts, except: [:index]
  namespace :admin do
  	resources :accounts
  	resources :addresses
  	resources :orders do
      collection do
        get :processed, :unprocessed
      end
    end

  end
end

app/models/account.rb
class Account < ApplicationRecord

	# associations
	belongs_to :user
	has_many :addresses, dependent: :delete_all
	has_many :orders, dependent: :delete_all

	accepts_nested_attributes_for :addresses

	# validations
	validates :phone_number, presence: true,
							 length: { is: 10 }, 
							 numericality: true
	validates :institution_name, presence: true
	validates :institution_type, presence: true
	validates :contact_first_name, presence: true
	validates :contact_last_name, presence: true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	include AccountsHelper
	
	before_action :has_account?, only: [:new]
	before_action :my_account?, only: [:show, :edit]

	def show
		@account = Account.find(params[:id])
	end

	def new
	  @account = Account.new
	  @account.addresses.build
	end

	def create
	  account_attributes = filter_params(account_new_params)
	  @account = current_user.build_account(account_attributes)
	  if @account.save
	  	flash[:success] = "Account info saved!"
		redirect_back_or(account_path(@account))
	  else
	  	render :new
	  end
	end

	def edit
		@account = Account.find(params[:id])
	end

	def update
		account_attributes = filter_params(account_edit_params)
		@account = Account.find(params[:id])
		@account.update_attributes(account_attributes)
		if @account.save
			flash[:success] = "Account info updated!"
			redirect_to account_path(@account)
		else
			render :edit
		end
	end


	private

	  def account_new_params
	  	params.require(:account).permit(:institution_name,
	  									:institution_type,
	  									:contact_first_name,
	  									:contact_last_name,
	  									:phone_number,
	  									:other_type,
	  									addresses_attributes: 
	  									[:street_address, :city,
	  									 :state, :zipcode])
	  end

	  def account_edit_params
	  	params.require(:account).permit(:institution_name,
	  									:institution_type,
	  									:contact_first_name,
	  									:contact_last_name,
	  									:phone_number,
	  									:other_type)
	  end

	  def filter_params(params_hash)
	    unless params_hash[:other_type] == ""
	      params_hash[:institution_type] = params_hash[:other_type]
	    end
	    params_hash.delete(:other_type)
	    params_hash
	  end

	  def has_account?
	  	redirect_to root_path if current_user_account
	  end

	  def my_account?
	  	unless current_user.admin?
	  	  unless current_user_account.id == params[:id].to_i
	  	  	redirect_to root_path
	  	  end
	  	end
	  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
	def institution_types
	  [
	  	["Medical", "Medical"],
	  	["Essential Services", "Essential Services"],
	  	["Physical Therapy/Occupational Therapy", 
	  	 "Physical Therapy/Occupational Therapy"],
	  	["Assisted Living and Memory Care", 
	  	 "Assisted Living and Memory Care"],
	  	["Community Mental Health",
	  	 "Community Mental Health"],
	  	["Other", "Other"]
	  ]
	end

	def us_states
          [
            ['Alabama', 'AL'],
            ['Alaska', 'AK'],
            ['Arizona', 'AZ'],
            ['Arkansas', 'AR'],
            ['California', 'CA'],
            ['Colorado', 'CO'],
            ['Connecticut', 'CT'],
            ['Delaware', 'DE'],
            ['District of Columbia', 'DC'],
            ['Florida', 'FL'],
            ['Georgia', 'GA'],
            ['Hawaii', 'HI'],
            ['Idaho', 'ID'],
            ['Illinois', 'IL'],
            ['Indiana', 'IN'],
            ['Iowa', 'IA'],
            ['Kansas', 'KS'],
            ['Kentucky', 'KY'],
            ['Louisiana', 'LA'],
            ['Maine', 'ME'],
            ['Maryland', 'MD'],
            ['Massachusetts', 'MA'],
            ['Michigan', 'MI'],
            ['Minnesota', 'MN'],
            ['Mississippi', 'MS'],
            ['Missouri', 'MO'],
            ['Montana', 'MT'],
            ['Nebraska', 'NE'],
            ['Nevada', 'NV'],
            ['New Hampshire', 'NH'],
            ['New Jersey', 'NJ'],
            ['New Mexico', 'NM'],
            ['New York', 'NY'],
            ['North Carolina', 'NC'],
            ['North Dakota', 'ND'],
            ['Ohio', 'OH'],
            ['Oklahoma', 'OK'],
            ['Oregon', 'OR'],
            ['Pennsylvania', 'PA'],
            ['Puerto Rico', 'PR'],
            ['Rhode Island', 'RI'],
            ['South Carolina', 'SC'],
            ['South Dakota', 'SD'],
            ['Tennessee', 'TN'],
            ['Texas', 'TX'],
            ['Utah', 'UT'],
            ['Vermont', 'VT'],
            ['Virginia', 'VA'],
            ['Washington', 'WA'],
            ['West Virginia', 'WV'],
            ['Wisconsin', 'WI'],
            ['Wyoming', 'WY']
          ]
    end

    def pluralize_address(count, word)
      if count == 1
        return word
      else
        return word + "es"
      end
    end
end

app/views/accounts/edit.html.erb
<div class="main-wrapper">

<h1 class="page-title">Edit Account Info</h1>

<%= form_with(model: @account, local: true, class: "account-edit-form") do |f| %>
  <span style="display: none" id="institution_type"><%= @account.institution_type %></span>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="institution">
  	  <h2>Institution</h2>
	  <div class="form-group">
	    <%= f.label :institution_name, "Institution Name" %>
	    <%= f.text_field :institution_name, class: "form-control" %>
	  </div>
	  <div class="form-group">
	    <%= f.label :institution_type, "Institution Type" %>
	    <%= f.select :institution_type, options_for_select(institution_types, @account.institution_type), {}, class: "form-control" %>
	  </div>
	  <div id="other-div" style="display: none">
	  	<%= f.label :other_type, "Please specify:" %>
	  	<%= f.text_field :other_type %>
	  </div>
  </div>
	  <div class="contact">
	  	<h2>Primary Contact</h2>
	  	<div class="form-group">
	    <%= f.label :contact_first_name, "First Name" %>
	    <%= f.text_field :contact_first_name, class: "form-control" %>
	  </div>
	    <%= f.label :contact_last_name, "Last Name" %>
	    <%= f.text_field :contact_last_name, class: "form-control" %>
	  <div class="form-group">
	    <%= f.label :phone_number, "Phone Number" %>
	    <%= f.telephone_field :phone_number, class: "form-control" %>
	  </div>
  </div>
  <div class="form-group d-flex justify-content-center">
    <%= f.submit "Update Account", class: "btn btn-secondary" %>
  </div>
<% end %>
</div>

app/views/accounts/new.html.erb
<div class="main-wrapper">
<h1 class="page-title">Account Information</h1>

<%= form_with(model: @account, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="institution">
  	  <h2>Institution</h2>
	  <div class="form-group">
	    <%= f.label :institution_name, "Institution Name" %>
	    <%= f.text_field :institution_name, class: "form-control" %>
	  </div>
	  <div class="form-group">
	    <%= f.label :institution_type, "Institution Type" %>
	    <%= f.select :institution_type, options_for_select(institution_types), {}, class: "form-control" %>
	  </div>
	  <div id="other-div" style="display: none">
	  	<%= f.label :other_type, "Please specify:" %>
	  	<%= f.text_field :other_type %>
	  </div>
  </div>
	  <div class="contact">
	  	<h2>Primary Contact</h2>
	  	<div class="form-group">
	    <%= f.label :contact_first_name, "First Name" %>
	    <%= f.text_field :contact_first_name, class: "form-control" %>
	  </div>
	    <%= f.label :contact_last_name, "Last Name" %>
	    <%= f.text_field :contact_last_name, class: "form-control" %>
	  <div class="form-group">
	    <%= f.label :phone_number, "Phone Number" %>
	    <%= f.telephone_field :phone_number, class: "form-control" %>
	  </div>
  </div>
  <div class="address">
  	<h2>Address</h2>
  	<span>You can associate more addresses with this account later if you'd like.</span>
  	<%= f.fields_for :addresses do |addresses_form| %>
  	  <div class="form-group">
  	    <%= addresses_form.label :street_address, "Street Address" %>
  	    <%= addresses_form.text_field :street_address, class: "form-control" %>
  	 </div>
  	 <div class="form-group">
  	    <%= addresses_form.label :city %>
  	    <%= addresses_form.text_field :city, class: "form-control" %>
  	 </div>
  	 <div class="form-group">
  	    <%= addresses_form.label :state %>
  	    <%= addresses_form.select :state, options_for_select(us_states, "IL"), {}, class: "form-control" %>
  	 </div>
  	 <div class="form-group">
  	    <%= addresses_form.label :zipcode %>
  	    <%= addresses_form.text_field :zipcode, class: "form-control" %>
  	 </div>
  	<% end %>
  </div>
  <div class="form-group d-flex justify-content-center">
    <%= f.submit "Save", class: "btn btn-secondary" %>
  </div>
<% end %>
</div>

app/views/accounts/show.html.erb
<div class="main-wrapper">
<div class="card account-info">
	<h1 class="card-header">Account</h1>
	<ul class="list-group">
		<li class="list-group-item info-group">
			<div class="info">
			  <h2>Login</h2>
			  <span>Email:</span>
			  <%= @account.user.email %>
			  <span class="no-bold suggestion">(click pencil icon to change password)</span>
			</div>
			<div class="buttons">
			  <%= link_to edit_user_registration_path(current_user) do %>
				<i class="material-icons">edit</i>
			  <% end %>
			  <%= link_to user_registration_path, data: { confirm: "Are you sure?" }, method: :delete do %>
				Cancel My Account
			  <% end %>
			</div>
		</li>
		<li class="list-group-item info-group">
			<div class="info">
				<h2>Institution</h2>
				<span>Name:</span>
				<%= @account.institution_name %>
				<span>Type:</span>
				<%= @account.institution_type %>
				<h2>Contact</h2>
			    <span>Name:</span>
			    <%= @account.contact_first_name %>
			    <%= @account.contact_last_name %>
			    <span>Phone:</span>
			    <%= @account.phone_number %>
			</div>
			<div class="buttons">
			  <%= link_to edit_account_path(@account) do %>
				<i class="material-icons">edit</i>
			  <% end %>
			</div>
		</li>
		<li class="list-group-item addresses-li">
			<h2><%= pluralize_address(@account.addresses.count, "Address") %></h2>
			<ul class="list-group">
				<% @account.addresses.each do |address| %>
				  <li class="list-group-item info-group address-info">
				  	<div class="info">
				  	  <span>Street Address:</span>
				      <%= address.street_address %>
				      <span>City:</span>
				      <%= address.city %>
				      <span>State:</span>
				      <%= address.state %>
				      <span>Zip Code:</span>
				      <%= address.zipcode %>
				    </div>
				    <div class="buttons">
					  <%= link_to edit_address_path(address) do %>
				        <i class="material-icons">edit</i>
				      <% end %>
				      <%= link_to address_path(address), data: { confirm: "Are you sure want to delete this address?" },method: :delete do %>
				        <i class="material-icons">delete_outline</i>
				      <% end %>
				    </div>
				  </li>
				<% end %>
				<div class="buttons" id="add-address">
				  <%= link_to new_address_path do %>
				    <i class="material-icons">add_circle_outline</i>
			        <span class="no-bold"> Add A New Address</span>
			      <% end %>
			    </div>
			</ul>
		</li>
	</ul>
</div>
</div>